# Basic site settings
title: Szabolcs Kovács
email: szabolcs.kovacs.uni@gmail.com
description: An academic page for me.
baseurl: ""
url: "https://szabolcs-kovacs.github.io/"

# Remote theme configuration
remote_theme: daviddarnes/alembic  # Replace with the actual repository and tag of the theme.
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji               
